spring:
  datasource:
    url: jdbc:h2:mem:securitydb
    driverClassName: org.h2.Driver
    username: sa
    password: 
    generate-unique-name: false
    name: securtydb 
  jpa:
    show-sql: true  
  logging:
    level:
      org.springframework.jdbc.datasource.init: DEBUG   
  h2:
    console:
      enabled: true
      path: /h2-console
  file:
    path:
      name: metadata.json
  validFields:
      key: fields,sort,filter,format,page,per_page